"""secondary_for_trip_service_dump

Revision ID: 003
Revises: 002
Create Date: 2026-01-23 11:05:37.068716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_service_dump_file',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dump_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['dump_id'], ['trip_service_dump.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dump_id', 'file_id', name='uq_dump_file')
    )
    op.drop_constraint(op.f('trip_service_dump_file_id_fkey'), 'trip_service_dump', type_='foreignkey')
    op.drop_column('trip_service_dump', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_service_dump', sa.Column('file_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.execute(
        """
        UPDATE trip_service_dump AS tsd
        SET file_id = tdf.file_id
        FROM (
            SELECT dump_id, MIN(file_id) AS file_id
            FROM trip_service_dump_file
            GROUP BY dump_id
        ) AS tdf
        WHERE tsd.id = tdf.dump_id
        """
    )
    op.execute(
        """
        DELETE FROM trip_service_dump
        WHERE id NOT IN (SELECT dump_id FROM trip_service_dump_file)
        """
    )
    op.alter_column('trip_service_dump', 'file_id', nullable=False)
    op.create_foreign_key(op.f('trip_service_dump_file_id_fkey'), 'trip_service_dump', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_table('trip_service_dump_file')
    # ### end Alembic commands ###
