// Code generated by MockGen. DO NOT EDIT.
// Source: server/internal/application/application.go
//
// Generated by this command:
//
//	mockgen -source=server/internal/application/application.go -destination=server/internal/grpc/mock_app_test.go -package=grpc -mock_names App=MockApp
//

// Package grpc is a generated GoMock package.
package grpc

import (
	context "context"
	reflect "reflect"
	domain "wifi-event-dispatcher/domain"
	rabbitmq "wifi-event-dispatcher/internal/rabbitmq"

	gomock "go.uber.org/mock/gomock"
)

// MockSubscriber is a mock of Subscriber interface.
type MockSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberMockRecorder
	isgomock struct{}
}

// MockSubscriberMockRecorder is the mock recorder for MockSubscriber.
type MockSubscriberMockRecorder struct {
	mock *MockSubscriber
}

// NewMockSubscriber creates a new mock instance.
func NewMockSubscriber(ctrl *gomock.Controller) *MockSubscriber {
	mock := &MockSubscriber{ctrl: ctrl}
	mock.recorder = &MockSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriber) EXPECT() *MockSubscriberMockRecorder {
	return m.recorder
}

// SubscribeChan mocks base method.
func (m *MockSubscriber) SubscribeChan(ctx context.Context, opt rabbitmq.SubscribeChanOptions) (*rabbitmq.ChanSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeChan", ctx, opt)
	ret0, _ := ret[0].(*rabbitmq.ChanSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeChan indicates an expected call of SubscribeChan.
func (mr *MockSubscriberMockRecorder) SubscribeChan(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeChan", reflect.TypeOf((*MockSubscriber)(nil).SubscribeChan), ctx, opt)
}

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// HandleEvent mocks base method.
func (m *MockApp) HandleEvent(ctx context.Context, event *domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleEvent indicates an expected call of HandleEvent.
func (mr *MockAppMockRecorder) HandleEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleEvent", reflect.TypeOf((*MockApp)(nil).HandleEvent), ctx, event)
}

// SubscribeAll mocks base method.
func (m *MockApp) SubscribeAll(ctx context.Context, truckID int) ([]*rabbitmq.ChanSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeAll", ctx, truckID)
	ret0, _ := ret[0].([]*rabbitmq.ChanSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeAll indicates an expected call of SubscribeAll.
func (mr *MockAppMockRecorder) SubscribeAll(ctx, truckID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeAll", reflect.TypeOf((*MockApp)(nil).SubscribeAll), ctx, truckID)
}
