load_definitions = /etc/rabbitmq/definitions.json

log.console = true
log.console.level = info
# log.console.level = debug

# vm_memory_high_watermark.absolute = 1GB
total_memory_available_override_value = 1GB
vm_memory_high_watermark.relative = 0.7

anonymous_login_user = anonymous_user
anonymous_login_pass = anonymous_pass
