image: ${CI_REGISTRY_BASE}/devops/base_image:ansible-master

stages:
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_DEPLOY_KEY_PRIVAT" > /tmp/deploy_key
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
  - mkdir -p ~/.ssh/
  - echo -e "StrictHostKeyChecking=no\nUserKnownHostsFile=/dev/null" > ~/.ssh/config
  - export ANSIBLE_CONFIG=${CI_PROJECT_DIR}/.ansible/ansible.cfg
  
  # Дописываем секреты в конец файла
  - |
    echo "" >> .env
    echo "NEXUS_ADMIN_PASSWORD=${NEXUS_ADMIN_PASSWORD}" >> .env


# linter:
#   stage: linter
#   tags:
#     - infra-cluster
#   script:
#     - ansible-lint *.yml

dispa-infra:
  stage: deploy
  tags:
    - infra-cluster
  script:
    - ls -n
    - cd .ansible
    - ansible-playbook -i inventory main.yml
  only:
    refs:
      - dev
    variables:
      - $CI_PIPELINE_SOURCE == "push"
