FROM dockerhub.timeweb.cloud/postgis/postgis:17-3.4

USER root
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       gnupg ca-certificates curl apt-transport-https \
       postgresql-17-pgrouting \
    && curl -fsSL https://packagecloud.io/timescale/timescaledb/gpgkey | gpg --dearmor -o /usr/share/keyrings/timescale.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/timescale.gpg] https://packagecloud.io/timescale/timescaledb/debian/ bullseye main" > /etc/apt/sources.list.d/timescaledb.list \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
       timescaledb-2-postgresql-17 timescaledb-tools \
    && rm -rf /var/lib/apt/lists/*

USER postgres
