services:
  redis:
    image: redis:7.4-alpine
    container_name: sync-service-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./_redis_data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sync-service-network

  nanomq:
    image: emqx/nanomq:0.24
    container_name: sync-service-nanomq
    ports:
      - "1883:1883"
    environment:
      NANOMQ_CONF_PATH: "/etc/nanomq.conf"
    volumes:
      - ./config/nanomq/nanomq.conf:/etc/nanomq.conf:ro
    networks:
      - sync-service-network

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: sync-service-rabbitmq
    hostname: rabbitmq-node
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # HTTP management UI
    volumes:
      - ./_rabbitmq_data:/var/lib/rabbitmq
      - ./config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    mem_limit: 1gb
    networks:
      - sync-service-network

  sync-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: dev
    container_name: sync-service
    environment:
      INSTANCE_ID: bort_4
      MODE: dev
      LOG_LEVEL: DEBUG
      DEBUG_MODE: 1
      MULTI_REPLICA_MODE: 0
      REDIS_URL: redis://redis:6379/0
      MQTT_BROKER_HOST: nanomq
      MQTT_BROKER_PORT: 1883
      AUTOREPUB_MQTT_BROKER_HOST: nanomq
      AUTOREPUB_MQTT_BROKER_PORT: 1883
      RABBITMQ_DSN: amqp://consumer_user:consumer_pass@rabbitmq:5672/
    ports:
      - "8000:8000"
    volumes:
      - ./app:/service/app
    depends_on:
      redis:
        condition: service_healthy
      nanomq:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - sync-service-network

  # nanomq-external:
  #   image: emqx/nanomq:0.24
  #   container_name: sync-service-nanomq-external
  #   ports:
  #     - "1882:1882"
  #   environment:
  #     NANOMQ_CONF_PATH: "/etc/nanomq.conf"
  #   volumes:
  #     - ./config/nanomq/nanomq.ext.conf:/etc/nanomq.conf:ro
  #   depends_on:
  #     nanomq:
  #       condition: service_started
  #   networks:
  #     - sync-service-network

networks:
  sync-service-network:
    name: sync-service-network
    driver: bridge
