services:
  nanomq-server:
    image: emqx/nanomq:0.24
    container_name: sync-service-nanomq-server
    ports:
      - "1884:1883"
    environment:
      NANOMQ_CONF_PATH: "/etc/nanomq.conf"
    volumes:
      - ./config/nanomq/nanomq.srv.conf:/etc/nanomq.conf:ro
    networks:
      - sync-service-network

  sync-service-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: dev
    # container_name: sync-service-server
    # ports:
    #   - "8001:8000"
    deploy:
      replicas: 1
    ports:
      - "8001-8010:8000"
    environment:
      INSTANCE_ID: server
      MODE: dev
      LOG_LEVEL: DEBUG
      DEBUG_MODE: 1
      MULTI_REPLICA_MODE: 1
      REMOTE_INSTANCES: bort_4,bort_9,bort_17
      REDIS_URL: redis://redis:6379/1
      MQTT_BROKER_HOST: nanomq-server
      MQTT_BROKER_PORT: 1883
      AUTOREPUB_MQTT_BROKER_HOST: nanomq-server
      AUTOREPUB_MQTT_BROKER_PORT: 1883
      RABBITMQ_DSN: amqp://consumer_user:consumer_pass@rabbitmq:5672/
    volumes:
      - ./app:/service/app
    depends_on:
      nanomq-server:
        condition: service_started
    networks:
      - sync-service-network

networks:
  sync-service-network:
    name: sync-service-network
    external: true
