## NanoMQ Configuration File

listeners.tcp {
  bind = "0.0.0.0:1882"
}

log {
  to = [console]
  level = info
}

auth {
  allow_anonymous = true
}

bridges {
  mqtt {

    external_to_self {
      # DEV DISPA BORT-1
      server = "mqtt-tcp://10.100.109.13:1883"
      proto_ver = 4
      clean_start = true

      subscription = [
        { remote_topic = "truck/#" local_topic = "" qos = 0 }
      ]

    }

    self_to_nanomq {
      server = "mqtt-tcp://nanomq:1883"
      proto_ver = 4
      clean_start = true

      forwards = [
        { local_topic = "truck/#" remote_topic = "" qos = 0 }
      ]

    }

  }
}
