services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER:     minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

    networks:
      backend:



  minio-setup:
    image: minio/mc:latest
    container_name: minio-setup
    depends_on:
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: ["/setup.sh"]
    volumes:
      - ./setup/setup_minio.sh:/setup.sh:ro
    environment:
      MINIO_HOST: http://minio:9000
      MINIO_USER: minioadmin
      MINIO_PASSWORD: minioadmin123
      BUCKET_NAME: mybucket
      EVENTS: "put"
      # AMQP target id (как раньше WEBHOOK_ARN_ID)
      AMQP_ARN_ID: PRIMARY

      # RabbitMQ connection
      AMQP_URL: "amqp://rabbit:rabbit@rabbitmq:5672/"
      AMQP_EXCHANGE: "minio.events"
      AMQP_ROUTING_KEY: "minio.mybucket"
      AMQP_EXCHANGE_TYPE: "topic"
      AMQP_DURABLE: "on"




    networks:
      backend:



  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:

  rabbitmq-init:
    image: curlimages/curl:8.6.0
    depends_on:
      rabbitmq:
        condition: service_healthy

    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "/setup.sh" ]
    volumes:
      - ./setup/setup_rabbitmq.sh:/setup.sh:ro
    environment:
      EXCHANGE: "minio.events"
      QUEUE: "minio-events"
      ROUTING_KEY: "minio.mybucket"
    networks:
      backend:
    restart: "no"


  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - "8123:8123"    # HTTP interface
      - "9005:9000"    # Native TCP client
      - "9009:9009"    # Inter-server HTTP (optional)
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "localhost:8123/ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

    networks:
      backend:



networks:
  backend:

volumes:
  minio_data:
  rabbitmq_data:
  clickhouse-data:
