x-trip-service-template: &trip-service-build
  build:
    context: ../repos/dispa-backend
    dockerfile: Dockerfile
    args:
      - CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SLUG}
      - CI_REGISTRY_USER=${CI_REGISTRY_USER}
      - CI_REGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD}

services:
  auth-service-backend:
    build:
      context: ../repos/auth-service-backend
      dockerfile: Dockerfile

  graph-service-backend:
    build:
      context: ../repos/graph-service-backend
      dockerfile: Dockerfile
      args:
        - CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SLUG}
        - CI_REGISTRY_USER=${CI_REGISTRY_USER}
        - CI_REGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD}
    volumes:
      # Hot reload для development
      - ../repos/graph-service-backend/app:/app/app
      - ../repos/graph-service-backend/config:/app/config
    extra_hosts:
      - "host.docker.internal:host-gateway"

  enterprise-service:
    build:
      context: ../repos/enterprise-service
      dockerfile: Dockerfile
      args:
        - CI_COMMIT_REF_SLUG=${CI_COMMIT_REF_SLUG}
        - CI_REGISTRY_USER=${CI_REGISTRY_USER}
        - CI_REGISTRY_PASSWORD=${CI_REGISTRY_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sync-service:
    build:
      context: ../repos/sync-service
      dockerfile: Dockerfile
    volumes:
      - ../repos/sync-service:/service/app

  dump-service:
    build:
      context: ../repos/dump-service
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cdc-bort-applier:
    build:
      context: ../repos/cdc-bort-applier
      dockerfile: Dockerfile
    container_name: dispatching-cdc-bort-applier
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wifi-event-dispatcher-bort:
    build:
      context: ../repos/wifi-event-dispatcher
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"

  trip-service:
    <<: *trip-service-build
    volumes:
      - ../repos/dispa-backend/src:/app/src

  trip-transport-service:
    <<: *trip-service-build
    volumes:
      - ../repos/dispa-backend/src:/app/src

  ekuiper:
    build:
      context: ../repos/ekuiper
      dockerfile: Dockerfile

  nanomq:
    build:
      context: ../repos/nanomq-bort-disp
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    build:
      context: ../repos/postgres-disp
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    build:
      context: ../repos/rabbitmq-bort-disp
      dockerfile: Dockerfile
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  bort-client:
    build:
      context: ../repos/bort-client
      dockerfile: Dockerfile
    volumes:
      - ../repos/bort-client:/app
