// Code generated by MockGen. DO NOT EDIT.
// Source: bort/internal/domain/server_repository.go
//
// Generated by this command:
//
//	mockgen -source=bort/internal/domain/server_repository.go -destination=bort/internal/application/mock_server_repository_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	serverpb "wifi-event-dispatcher/server/serverpb"

	gomock "go.uber.org/mock/gomock"
)

// MockServerRepository is a mock of ServerRepository interface.
type MockServerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServerRepositoryMockRecorder
	isgomock struct{}
}

// MockServerRepositoryMockRecorder is the mock recorder for MockServerRepository.
type MockServerRepositoryMockRecorder struct {
	mock *MockServerRepository
}

// NewMockServerRepository creates a new mock instance.
func NewMockServerRepository(ctrl *gomock.Controller) *MockServerRepository {
	mock := &MockServerRepository{ctrl: ctrl}
	mock.recorder = &MockServerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerRepository) EXPECT() *MockServerRepositoryMockRecorder {
	return m.recorder
}

// StreamGetEvents mocks base method.
func (m *MockServerRepository) StreamGetEvents(ctx context.Context) (serverpb.EventDispatchService_StreamBortGetEventsClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamGetEvents", ctx)
	ret0, _ := ret[0].(serverpb.EventDispatchService_StreamBortGetEventsClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamGetEvents indicates an expected call of StreamGetEvents.
func (mr *MockServerRepositoryMockRecorder) StreamGetEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamGetEvents", reflect.TypeOf((*MockServerRepository)(nil).StreamGetEvents), ctx)
}

// StreamSendEvents mocks base method.
func (m *MockServerRepository) StreamSendEvents(ctx context.Context) (serverpb.EventDispatchService_StreamBortSendEventsClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamSendEvents", ctx)
	ret0, _ := ret[0].(serverpb.EventDispatchService_StreamBortSendEventsClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamSendEvents indicates an expected call of StreamSendEvents.
func (mr *MockServerRepositoryMockRecorder) StreamSendEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamSendEvents", reflect.TypeOf((*MockServerRepository)(nil).StreamSendEvents), ctx)
}
