// Code generated by MockGen. DO NOT EDIT.
// Source: bort/internal/application/application.go
//
// Generated by this command:
//
//	mockgen -source=bort/internal/application/application.go -destination=bort/internal/application/mock_deps_test.go -package=application -mock_names EventPublisher=MockEventPublisher,RabbitSubscriber=MockRabbitSubscriber
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	rabbitmq "wifi-event-dispatcher/internal/rabbitmq"

	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventPublisher) Publish(ctx context.Context, msg rabbitmq.PublishMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventPublisherMockRecorder) Publish(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventPublisher)(nil).Publish), ctx, msg)
}

// MockRabbitSubscriber is a mock of RabbitSubscriber interface.
type MockRabbitSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockRabbitSubscriberMockRecorder
	isgomock struct{}
}

// MockRabbitSubscriberMockRecorder is the mock recorder for MockRabbitSubscriber.
type MockRabbitSubscriberMockRecorder struct {
	mock *MockRabbitSubscriber
}

// NewMockRabbitSubscriber creates a new mock instance.
func NewMockRabbitSubscriber(ctrl *gomock.Controller) *MockRabbitSubscriber {
	mock := &MockRabbitSubscriber{ctrl: ctrl}
	mock.recorder = &MockRabbitSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRabbitSubscriber) EXPECT() *MockRabbitSubscriberMockRecorder {
	return m.recorder
}

// SubscribeChan mocks base method.
func (m *MockRabbitSubscriber) SubscribeChan(ctx context.Context, opt rabbitmq.SubscribeChanOptions) (*rabbitmq.ChanSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeChan", ctx, opt)
	ret0, _ := ret[0].(*rabbitmq.ChanSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeChan indicates an expected call of SubscribeChan.
func (mr *MockRabbitSubscriberMockRecorder) SubscribeChan(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeChan", reflect.TypeOf((*MockRabbitSubscriber)(nil).SubscribeChan), ctx, opt)
}

// MockDedupService is a mock of dedup.Service interface.
type MockDedupService struct {
	ctrl     *gomock.Controller
	recorder *MockDedupServiceMockRecorder
}

type MockDedupServiceMockRecorder struct {
	mock *MockDedupService
}

func NewMockDedupService(ctrl *gomock.Controller) *MockDedupService {
	mock := &MockDedupService{ctrl: ctrl}
	mock.recorder = &MockDedupServiceMockRecorder{mock}
	return mock
}

func (m *MockDedupService) EXPECT() *MockDedupServiceMockRecorder {
	return m.recorder
}

func (m *MockDedupService) IsDuplicate(ctx context.Context, messageID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDuplicate", ctx, messageID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDedupServiceMockRecorder) IsDuplicate(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDuplicate", reflect.TypeOf((*MockDedupService)(nil).IsDuplicate), ctx, messageID)
}

func (m *MockDedupService) MarkSeen(ctx context.Context, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSeen", ctx, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDedupServiceMockRecorder) MarkSeen(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSeen", reflect.TypeOf((*MockDedupService)(nil).MarkSeen), ctx, messageID)
}

// MockQueueDiscoverer is a mock of QueueDiscoverer interface.
type MockQueueDiscoverer struct {
	ctrl     *gomock.Controller
	recorder *MockQueueDiscovererMockRecorder
}

type MockQueueDiscovererMockRecorder struct {
	mock *MockQueueDiscoverer
}

func NewMockQueueDiscoverer(ctrl *gomock.Controller) *MockQueueDiscoverer {
	mock := &MockQueueDiscoverer{ctrl: ctrl}
	mock.recorder = &MockQueueDiscovererMockRecorder{mock}
	return mock
}

func (m *MockQueueDiscoverer) EXPECT() *MockQueueDiscovererMockRecorder {
	return m.recorder
}

func (m *MockQueueDiscoverer) DiscoverQueues(ctx context.Context, nameRegex string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverQueues", ctx, nameRegex)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockQueueDiscovererMockRecorder) DiscoverQueues(ctx, nameRegex any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverQueues", reflect.TypeOf((*MockQueueDiscoverer)(nil).DiscoverQueues), ctx, nameRegex)
}

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockApp) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAppMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockApp)(nil).Start), ctx)
}
