services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"  # UI
      - "5552:5552"    # RabbitMQ Streams (native stream protocol)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: "SOME_RANDOM_COOKIE"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./.docker/config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./.docker/config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    command: >
      bash -lc "
        rabbitmq-plugins enable --offline rabbitmq_stream rabbitmq_management &&
        rabbitmq-server
      "
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      backend:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trip_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # Включаем logical replication (для Debezium)
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 10s
      timeout: 5s
      retries: 12

    networks:
      backend:

  debezium-server:
    image: debezium/server:3.0.0.Final
    container_name: debezium-server
    hostname: debezium-server
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./.docker/config/debezium/application.properties:/debezium/config/application.properties:ro
      - debezium_data:/debezium/data
    networks:
      backend:
#    restart: on-failure

networks:
  backend:

volumes:
  rabbitmq_data:
  postgres_data:
  debezium_data:
