"""add Boolean fields to role_permission table

Revision ID: 004
Revises: 003
Create Date: 2026-02-25 11:28:44.505896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('can_view', sa.Boolean(), nullable=False))
    op.add_column('role_permissions', sa.Column('can_edit', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'staff', ['phone'])
    op.create_unique_constraint(None, 'staff', ['personnel_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('role_permissions', 'can_edit')
    op.drop_column('role_permissions', 'can_view')
    # ### end Alembic commands ###

