services:
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  server:
    build: .
    restart: unless-stopped
    entrypoint: ["/server"]

    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      ENVIRONMENT: ${ENVIRONMENT}

    depends_on:
      - rabbitmq

  bort:
    build: .
    restart: unless-stopped
    entrypoint: ["/bort"]

    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      BORT_TRUCK_ID: ${BORT_TRUCK_ID}
      BORT_NANOMQ_HOST: ${BORT_NANOMQ_HOST}
      BORT_NANOMQ_PORT: ${BORT_NANOMQ_PORT}
      BORT_SERVER_ADDRESS: server:8085
      ENVIRONMENT: ${ENVIRONMENT}
      COORDINATION_URL: ${COORDINATION_URL}
      DISTRIBUTION_URL: ${DISTRIBUTION_URL}
      AUTOREPUB_HTTP_TIMEOUT: ${AUTOREPUB_HTTP_TIMEOUT}

    depends_on:
      - rabbitmq
      - server

volumes:
  rabbitmq_data:
