"""initial_schema

Revision ID: 001
Revises: 
Create Date: 2025-12-18 09:49:20.320307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CREATED', 'SYNCED', name='syncstatus').create(op.get_bind())
    op.create_table('file',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sync_status', postgresql.ENUM('CREATED', 'SYNCED', name='syncstatus', create_type=False), nullable=False),
    sa.Column('trip_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path'),
    sa.UniqueConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    sa.Enum('CREATED', 'SYNCED', name='syncstatus').drop(op.get_bind())
    # ### end Alembic commands ###
