"""add trip_service_dump table

Revision ID: 002
Revises: 001
Create Date: 2025-12-24 12:00:22.260235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_service_dump',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    op.drop_constraint(op.f('file_trip_id_key'), 'file', type_='unique')
    op.drop_column('file', 'trip_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('trip_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, default="null"))
    op.create_unique_constraint(op.f('file_trip_id_key'), 'file', ['trip_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('trip_service_dump')
    # ### end Alembic commands ###
