## NanoMQ Configuration File

mqtt {
  port = 1883
  max_connections = 1024000
  max_packet_size = 10485760
  keepalive_backoff = 1.25
  max_inflight_messages = 1000
  max_queued_messages = 5000
  retry_interval = 5

  lmq_size = 10000
  aio_threads = 16
}

websocket {
  enable = true
  port = 8083
  path = "/mqtt"
}

http_server {
  enable = true
  port = 8081
  username = "admin"
  password = "public"
}

log {
  to = [console]
  level = info
}

auth {
  allow_anonymous = true
  clean_start = false
}

bridges {
  mqtt {

    server_bridge {
      server = "mqtt-tcp://SERVER_NANOMQ_HOST_PLACEHOLDER:SERVER_NANOMQ_PORT_PLACEHOLDER"
      proto_ver = 4
      clientid = "VEHICLE_ID_PLACEHOLDER"
      keepalive = 90
      clean_start = false

      reconnect_delay = 15
      max_reconnect_delay = 300

      max_parallel_processes = 32
      max_inflight_messages = 1000
      queue_len = 5000

      forwards = [
        { remote_topic = "" local_topic = "truck/VEHICLE_ID_PLACEHOLDER/sensor/+/events" qos = 1 }
        { remote_topic = "" local_topic = "truck/VEHICLE_ID_PLACEHOLDER/sensor/gps/ds" qos = 1 }
        { remote_topic = "" local_topic = "truck/VEHICLE_ID_PLACEHOLDER/trip-service/events" qos = 1 }

        { remote_topic = "" local_topic = "sync/SERVER_INSTANCE_ID_PLACEHOLDER/#" qos = 1 }
      ]

      subscription = [
        { remote_topic = "truck/VEHICLE_ID_PLACEHOLDER/enterprise-service/events" local_topic = "" qos = 1 }
        { remote_topic = "graph-service/events" local_topic = "" qos = 1 }

        { remote_topic = "sync/INSTANCE_ID_PLACEHOLDER/#" local_topic = "" qos = 1 }
      ]
    }

  }
}