"""audit_outbox

Revision ID: 015
Revises: 014
Create Date: 2026-03-03 14:23:40.951390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '015'
down_revision = '014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_outbox_entity', 'audit_outbox', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_outbox_processed', 'audit_outbox', ['processed'], unique=False)
    op.create_index('ix_audit_outbox_timestamp', 'audit_outbox', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_outbox_timestamp', table_name='audit_outbox')
    op.drop_index('ix_audit_outbox_processed', table_name='audit_outbox')
    op.drop_index('ix_audit_outbox_entity', table_name='audit_outbox')
    op.drop_table('audit_outbox')
    # ### end Alembic commands ###
