workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^(dev|staging|main)$/'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(dev|staging|main)$/'
      when: always
    - when: never

include:
  - project: "k8s/gitlab-template"
    ref: "main"
    file: "/pypi-buld.yaml"
    
stages:
  - test
  - pypi

pytest:
  rules:
    - when: never
