services:
  sync-service-b9:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: dev
    environment:
      INSTANCE_ID: bort_9
      MODE: dev
      LOG_LEVEL: DEBUG
      DEBUG_MODE: 1
      MULTI_REPLICA_MODE: 0
      REDIS_URL: redis://redis:6379/2
      MQTT_BROKER_HOST: nanomq
      MQTT_BROKER_PORT: 1883
      AUTOREPUB_MQTT_BROKER_HOST: nanomq
      AUTOREPUB_MQTT_BROKER_PORT: 1883
      RABBITMQ_DSN: amqp://consumer_user:consumer_pass@rabbitmq:5672/
    ports:
      - "7999:8000"
    volumes:
      - ./app:/service/app
    networks:
      - sync-service-network

networks:
  sync-service-network:
    name: sync-service-network
    external: true
