stages:
  - test
  - scanner
  - build
  - trigger-deploy

default:
  tags:
    - infra-cluster

include:
  - project: "k8s/gitlab-template"
    ref: "main"
    file: "/dispa-build.gitlab-ci.yaml"


trigger-bort:
  stage: trigger-deploy
  extends: .trigger_dispatching_bort
  variables:
    SERVICE_NAME: ${CI_PROJECT_NAME}
