stages:
  - test
  - scanner
  - build
  - trigger-deploy

include:
  - project: "k8s/gitlab-template" 
    file: 'gotest.gitlab-ci.yaml'
    inputs:
      go_version: "1.25"
      cover_packages: "wifi-event-dispatcher/domain/...,wifi-event-dispatcher/bort/internal/application/...,wifi-event-dispatcher/server/internal/...,wifi-event-dispatcher/internal/config/...,wifi-event-dispatcher/internal/dedup/...,wifi-event-dispatcher/internal/redis/...,wifi-event-dispatcher/internal/fx/dedup/..."  
  - project: "k8s/gitlab-template"
    ref: "main"
    file: "/dispa-build.gitlab-ci.yaml"

trigger-bort:
  extends: .trigger_dispatching_bort
  variables:
    SERVICE_NAME_BORT: "wifi-event-dispatcher-bort"
    SERVICE_NAME_SERVER: "wifi-event-dispatcher-server"

trigger-server:
  extends: .trigger_dispatching_server
  variables:
    SERVICE_NAME_SERVER: "wifi-event-dispatcher-server"