## NanoMQ Configuration File

listeners.tcp {
  bind = "0.0.0.0:1883"
}

log {
  to = [console]
  level = info
}

auth {
  allow_anonymous = true
}

bridges {
  mqtt {

    server_to_bort {
      server = "mqtt-tcp://nanomq:1883"
      proto_ver = 5
      clean_start = true

      forwards = [
        { local_topic = "sync/bort_4/#" remote_topic = "" qos = 1 }
        { local_topic = "sync/bort_9/#" remote_topic = "" qos = 1 }
      ]

      subscription = [
        { remote_topic = "sync/server/#" local_topic = "" qos = 1 }
      ]
    }

  }
}
