stages:
  - test
  - scanner
  - build
  - trigger-deploy

default:
  tags:
    - infra-cluster

include:
  - project: 'k8s/gitlab-template'
    file: 'pytest.gitlab-ci.yaml'
    inputs:
      pre_commit: true
  - project: "k8s/gitlab-template"
    ref: "main"
    file: "/dispa-build.gitlab-ci.yaml"

trigger-trip-service-server:
  stage: trigger-deploy
  extends: .trigger_dispatching_server
  variables:
    SERVICE_NAME: trip-service-server

trigger-trip-transport-service-server:
  stage: trigger-deploy
  extends: .trigger_dispatching_server
  variables:
    SERVICE_NAME: trip-transport-service-server

trigger-trip-service:
  stage: trigger-deploy
  extends: .trigger_dispatching_bort
  variables:
    SERVICE_NAME: trip-service

trigger-trip-transport-service:
  stage: trigger-deploy
  extends: .trigger_dispatching_bort
  variables:
    SERVICE_NAME: trip-transport-service
