// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: serverpb/api.proto

package serverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_serverpb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_serverpb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_serverpb_api_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Event) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_serverpb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_serverpb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_serverpb_api_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*SendEventRequest_Producer
	//	*SendEventRequest_Event
	Kind          isSendEventRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEventRequest) Reset() {
	*x = SendEventRequest{}
	mi := &file_serverpb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEventRequest) ProtoMessage() {}

func (x *SendEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serverpb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEventRequest.ProtoReflect.Descriptor instead.
func (*SendEventRequest) Descriptor() ([]byte, []int) {
	return file_serverpb_api_proto_rawDescGZIP(), []int{2}
}

func (x *SendEventRequest) GetKind() isSendEventRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SendEventRequest) GetProducer() *Client {
	if x != nil {
		if x, ok := x.Kind.(*SendEventRequest_Producer); ok {
			return x.Producer
		}
	}
	return nil
}

func (x *SendEventRequest) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Kind.(*SendEventRequest_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isSendEventRequest_Kind interface {
	isSendEventRequest_Kind()
}

type SendEventRequest_Producer struct {
	Producer *Client `protobuf:"bytes,1,opt,name=producer,proto3,oneof"`
}

type SendEventRequest_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*SendEventRequest_Producer) isSendEventRequest_Kind() {}

func (*SendEventRequest_Event) isSendEventRequest_Kind() {}

type SendEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           *Ack                   `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEventResponse) Reset() {
	*x = SendEventResponse{}
	mi := &file_serverpb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEventResponse) ProtoMessage() {}

func (x *SendEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serverpb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEventResponse.ProtoReflect.Descriptor instead.
func (*SendEventResponse) Descriptor() ([]byte, []int) {
	return file_serverpb_api_proto_rawDescGZIP(), []int{3}
}

func (x *SendEventResponse) GetAck() *Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TruckId       int32                  `protobuf:"varint,1,opt,name=truck_id,json=truckId,proto3" json:"truck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_serverpb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_serverpb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_serverpb_api_proto_rawDescGZIP(), []int{4}
}

func (x *Client) GetTruckId() int32 {
	if x != nil {
		return x.TruckId
	}
	return 0
}

type GetEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*GetEventRequest_Subscriber
	//	*GetEventRequest_Ack
	Kind          isGetEventRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_serverpb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serverpb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_serverpb_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventRequest) GetKind() isGetEventRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *GetEventRequest) GetSubscriber() *Client {
	if x != nil {
		if x, ok := x.Kind.(*GetEventRequest_Subscriber); ok {
			return x.Subscriber
		}
	}
	return nil
}

func (x *GetEventRequest) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Kind.(*GetEventRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isGetEventRequest_Kind interface {
	isGetEventRequest_Kind()
}

type GetEventRequest_Subscriber struct {
	Subscriber *Client `protobuf:"bytes,1,opt,name=subscriber,proto3,oneof"`
}

type GetEventRequest_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*GetEventRequest_Subscriber) isGetEventRequest_Kind() {}

func (*GetEventRequest_Ack) isGetEventRequest_Kind() {}

type GetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_serverpb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serverpb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_serverpb_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_serverpb_api_proto protoreflect.FileDescriptor

const file_serverpb_api_proto_rawDesc = "" +
	"\n" +
	"\x12serverpb/api.proto\x12\bserverpb\"V\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"J\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"s\n" +
	"\x10SendEventRequest\x12.\n" +
	"\bproducer\x18\x01 \x01(\v2\x10.serverpb.ClientH\x00R\bproducer\x12'\n" +
	"\x05event\x18\x02 \x01(\v2\x0f.serverpb.EventH\x00R\x05eventB\x06\n" +
	"\x04kind\"4\n" +
	"\x11SendEventResponse\x12\x1f\n" +
	"\x03ack\x18\x01 \x01(\v2\r.serverpb.AckR\x03ack\"#\n" +
	"\x06Client\x12\x19\n" +
	"\btruck_id\x18\x01 \x01(\x05R\atruckId\"p\n" +
	"\x0fGetEventRequest\x122\n" +
	"\n" +
	"subscriber\x18\x01 \x01(\v2\x10.serverpb.ClientH\x00R\n" +
	"subscriber\x12!\n" +
	"\x03ack\x18\x02 \x01(\v2\r.serverpb.AckH\x00R\x03ackB\x06\n" +
	"\x04kind\"9\n" +
	"\x10GetEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.serverpb.EventR\x05event2\xbd\x01\n" +
	"\x14EventDispatchService\x12S\n" +
	"\x14StreamBortSendEvents\x12\x1a.serverpb.SendEventRequest\x1a\x1b.serverpb.SendEventResponse(\x010\x01\x12P\n" +
	"\x13StreamBortGetEvents\x12\x19.serverpb.GetEventRequest\x1a\x1a.serverpb.GetEventResponse(\x010\x01B0Z.wifi-event-dispatcher/server/serverpb;serverpbb\x06proto3"

var (
	file_serverpb_api_proto_rawDescOnce sync.Once
	file_serverpb_api_proto_rawDescData []byte
)

func file_serverpb_api_proto_rawDescGZIP() []byte {
	file_serverpb_api_proto_rawDescOnce.Do(func() {
		file_serverpb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serverpb_api_proto_rawDesc), len(file_serverpb_api_proto_rawDesc)))
	})
	return file_serverpb_api_proto_rawDescData
}

var file_serverpb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_serverpb_api_proto_goTypes = []any{
	(*Event)(nil),             // 0: serverpb.Event
	(*Ack)(nil),               // 1: serverpb.Ack
	(*SendEventRequest)(nil),  // 2: serverpb.SendEventRequest
	(*SendEventResponse)(nil), // 3: serverpb.SendEventResponse
	(*Client)(nil),            // 4: serverpb.Client
	(*GetEventRequest)(nil),   // 5: serverpb.GetEventRequest
	(*GetEventResponse)(nil),  // 6: serverpb.GetEventResponse
}
var file_serverpb_api_proto_depIdxs = []int32{
	4, // 0: serverpb.SendEventRequest.producer:type_name -> serverpb.Client
	0, // 1: serverpb.SendEventRequest.event:type_name -> serverpb.Event
	1, // 2: serverpb.SendEventResponse.ack:type_name -> serverpb.Ack
	4, // 3: serverpb.GetEventRequest.subscriber:type_name -> serverpb.Client
	1, // 4: serverpb.GetEventRequest.ack:type_name -> serverpb.Ack
	0, // 5: serverpb.GetEventResponse.event:type_name -> serverpb.Event
	2, // 6: serverpb.EventDispatchService.StreamBortSendEvents:input_type -> serverpb.SendEventRequest
	5, // 7: serverpb.EventDispatchService.StreamBortGetEvents:input_type -> serverpb.GetEventRequest
	3, // 8: serverpb.EventDispatchService.StreamBortSendEvents:output_type -> serverpb.SendEventResponse
	6, // 9: serverpb.EventDispatchService.StreamBortGetEvents:output_type -> serverpb.GetEventResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_serverpb_api_proto_init() }
func file_serverpb_api_proto_init() {
	if File_serverpb_api_proto != nil {
		return
	}
	file_serverpb_api_proto_msgTypes[2].OneofWrappers = []any{
		(*SendEventRequest_Producer)(nil),
		(*SendEventRequest_Event)(nil),
	}
	file_serverpb_api_proto_msgTypes[5].OneofWrappers = []any{
		(*GetEventRequest_Subscriber)(nil),
		(*GetEventRequest_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serverpb_api_proto_rawDesc), len(file_serverpb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serverpb_api_proto_goTypes,
		DependencyIndexes: file_serverpb_api_proto_depIdxs,
		MessageInfos:      file_serverpb_api_proto_msgTypes,
	}.Build()
	File_serverpb_api_proto = out.File
	file_serverpb_api_proto_goTypes = nil
	file_serverpb_api_proto_depIdxs = nil
}
