// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: serverpb/api.proto

package serverpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventDispatchService_StreamBortSendEvents_FullMethodName = "/serverpb.EventDispatchService/StreamBortSendEvents"
	EventDispatchService_StreamBortGetEvents_FullMethodName  = "/serverpb.EventDispatchService/StreamBortGetEvents"
)

// EventDispatchServiceClient is the client API for EventDispatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventDispatchServiceClient interface {
	StreamBortSendEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendEventRequest, SendEventResponse], error)
	StreamBortGetEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetEventRequest, GetEventResponse], error)
}

type eventDispatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventDispatchServiceClient(cc grpc.ClientConnInterface) EventDispatchServiceClient {
	return &eventDispatchServiceClient{cc}
}

func (c *eventDispatchServiceClient) StreamBortSendEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendEventRequest, SendEventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventDispatchService_ServiceDesc.Streams[0], EventDispatchService_StreamBortSendEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendEventRequest, SendEventResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventDispatchService_StreamBortSendEventsClient = grpc.BidiStreamingClient[SendEventRequest, SendEventResponse]

func (c *eventDispatchServiceClient) StreamBortGetEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetEventRequest, GetEventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventDispatchService_ServiceDesc.Streams[1], EventDispatchService_StreamBortGetEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetEventRequest, GetEventResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventDispatchService_StreamBortGetEventsClient = grpc.BidiStreamingClient[GetEventRequest, GetEventResponse]

// EventDispatchServiceServer is the server API for EventDispatchService service.
// All implementations must embed UnimplementedEventDispatchServiceServer
// for forward compatibility.
type EventDispatchServiceServer interface {
	StreamBortSendEvents(grpc.BidiStreamingServer[SendEventRequest, SendEventResponse]) error
	StreamBortGetEvents(grpc.BidiStreamingServer[GetEventRequest, GetEventResponse]) error
	mustEmbedUnimplementedEventDispatchServiceServer()
}

// UnimplementedEventDispatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventDispatchServiceServer struct{}

func (UnimplementedEventDispatchServiceServer) StreamBortSendEvents(grpc.BidiStreamingServer[SendEventRequest, SendEventResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamBortSendEvents not implemented")
}
func (UnimplementedEventDispatchServiceServer) StreamBortGetEvents(grpc.BidiStreamingServer[GetEventRequest, GetEventResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamBortGetEvents not implemented")
}
func (UnimplementedEventDispatchServiceServer) mustEmbedUnimplementedEventDispatchServiceServer() {}
func (UnimplementedEventDispatchServiceServer) testEmbeddedByValue()                              {}

// UnsafeEventDispatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventDispatchServiceServer will
// result in compilation errors.
type UnsafeEventDispatchServiceServer interface {
	mustEmbedUnimplementedEventDispatchServiceServer()
}

func RegisterEventDispatchServiceServer(s grpc.ServiceRegistrar, srv EventDispatchServiceServer) {
	// If the following call panics, it indicates UnimplementedEventDispatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventDispatchService_ServiceDesc, srv)
}

func _EventDispatchService_StreamBortSendEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventDispatchServiceServer).StreamBortSendEvents(&grpc.GenericServerStream[SendEventRequest, SendEventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventDispatchService_StreamBortSendEventsServer = grpc.BidiStreamingServer[SendEventRequest, SendEventResponse]

func _EventDispatchService_StreamBortGetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventDispatchServiceServer).StreamBortGetEvents(&grpc.GenericServerStream[GetEventRequest, GetEventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventDispatchService_StreamBortGetEventsServer = grpc.BidiStreamingServer[GetEventRequest, GetEventResponse]

// EventDispatchService_ServiceDesc is the grpc.ServiceDesc for EventDispatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventDispatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.EventDispatchService",
	HandlerType: (*EventDispatchServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBortSendEvents",
			Handler:       _EventDispatchService_StreamBortSendEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamBortGetEvents",
			Handler:       _EventDispatchService_StreamBortGetEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "serverpb/api.proto",
}
