default:
  interval: 1000  # ?
  url: postgres://postgres:postgres@db:5432/test_ugmk?sslmode=disable
  internalSqlQueryCfg:
    table: geometry_tag

  lookup:
    cache: true
    cacheTtl: 3000
    cacheMissingKey: true
