resolver 127.0.0.11 valid=1s ipv6=off;
resolver_timeout 2s;

server {
  listen 80;
  server_name _;

  access_log /dev/stdout;
  error_log /dev/stderr;
  client_max_body_size 200M;

  root /usr/share/nginx/html;
  index index.html;

  location /assets/ {
    alias /usr/share/nginx/html/assets/;
    expires 30d;
    add_header Cache-Control "public, max-age=2592000, immutable";
    try_files $uri =404;
  }

  location /favicon.ico {
    alias /usr/share/nginx/html/favicon.ico;
    expires 30d;
    add_header Cache-Control "public, max-age=2592000, immutable";
  }

  location / {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /index.html;
  }

 location /ws/vehicle-tracking {
    proxy_pass http://graph-service-backend:5000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 86400;
    proxy_send_timeout 86400;
    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;
}

  location /api/ {
      proxy_pass http://api-gateway:8000;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Connection "";
      proxy_buffering off;
  }
}
