"""add required fields to staff

Revision ID: 003
Revises: 002
Create Date: 2026-02-12 09:12:21.184062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('staff', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('staff', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('staff', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('staff', 'personnel_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('staff', 'personnel_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('staff', 'patronymic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('staff', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('staff', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###

