"""change hashed_password column type to LargeBinary

Revision ID: 006
Revises: 005
Create Date: 2026-03-02 12:24:31.271260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=True,
               postgresql_using="hashed_password::bytea"
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               # Добавляем инструкцию для PostgreSQL о конвертации данных при откате
               # ВНИМАНИЕ: если байты не были корректной строкой UTF-8, это может вызвать ошибку при откате
               postgresql_using="hashed_password::text"
               )
    # ### end Alembic commands ###
