
# =========================
# DEBUG logging
# =========================
quarkus.log.console.json=false
quarkus.log.level=INFO

quarkus.log.category."io.debezium.server.rabbitmq".level=DEBUG
quarkus.log.category."com.rabbitmq.stream".level=DEBUG
quarkus.log.category."com.rabbitmq.stream.impl".level=DEBUG


quarkus.log.category."io.smallrye.config".level=DEBUG

# =========================
# SINK: RabbitMQ Streams (native)
# =========================
debezium.sink.type=rabbitmqstream
debezium.sink.rabbitmqstream.connection.host=rabbitmq-server
debezium.sink.rabbitmqstream.connection.port=5552
debezium.sink.rabbitmqstream.connection.username=debezium_graph_service
debezium.sink.rabbitmqstream.connection.password=debezium_graph_service
debezium.sink.rabbitmqstream.connection.virtualHost=/
debezium.sink.rabbitmqstream.stream=cdc-graph-service



debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.password=postgres
debezium.source.database.dbname=dispatching_graph
debezium.source.plugin.name=pgoutput

debezium.source.topic.prefix=dispatching_graph


debezium.source.schema.include.list=public
debezium.source.table.exclude.list=public.alembic_version,public.vehicle_locations

debezium.source.slot.name=debezium_graph_slot
debezium.source.publication.autocreate.mode=filtered


debezium.source.snapshot.mode=initial


debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=1000
debezium.source.schema.history.internal.file.filename=/debezium/data/schemahistory.dat


debezium.transforms=unwrap
debezium.transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
debezium.transforms.unwrap.drop.tombstones=true
debezium.transforms.unwrap.delete.handling.mode=rewrite
