management.load_definitions = /etc/rabbitmq/definitions.json

# Если хотите явно включить stream listeners (обычно и так ок)
stream.listeners.tcp.default = 5552
stream.advertised_host = localhost
stream.advertised_port = 5552

# Allow guest user from non-loopback (Debezium stream client defaults to guest/guest)
loopback_users = none
