workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ /^(dev|staging|main)$/'

stages:
  - lint
  - test
  - scanner
  - build
  - trigger-deploy

default:
  tags:
    - infra-cluster

include:
  - project: 'k8s/gitlab-template'
    file: 'lint.gitlab-ci.yaml'
    inputs:
      frontend: true
  - project: "k8s/gitlab-template"
    ref: "main"
    file: "/dispa-build.gitlab-ci.yaml"

trigger-server:
  stage: trigger-deploy
  extends: .trigger_dispatching_server
  variables:
    SERVICE_NAME: ${CI_PROJECT_NAME}
