import logging
import os
import json
import re
import asyncio
import hashlib
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any

import requests
from sqlalchemy import select

from app.database import SessionLocal
from app.models.settings_model import Settings
from app.utils.runtime_config_manager import RuntimeConfigManager

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(name)s - %(message)s"
)
logger = logging.getLogger(__name__)
ENV_KEY_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class SettingsManager:

    def __init__(self):
        pass

    async def _get_latest_settings_from_db(self) -> Dict[str, Any]:
        """
        Получает последние настройки из БД.
        """
        async with SessionLocal() as session:
            try:
                result = await session.execute(
                    select(Settings).order_by(Settings.id.desc()).limit(1)
                )
                record = result.scalar_one_or_none()

                if record:
                    return record.secrets
                else:
                    logger.warning("No settings found in database. Initialization required.")
                    raise Exception("No settings found in database. Initialization required.")

            except Exception as e:
                logger.error(f"Failed to load settings from database: {e}")
                raise

    async def _save_settings_to_db(self, settings_data: Dict[str, Any]):
        """
        Сохраняет настройки в БД.
        """
        async with SessionLocal() as session:
            try:
                new_record = Settings(secrets=settings_data)
                session.add(new_record)
                await session.commit()
                logger.info("Settings saved to database successfully.")
            except Exception as e:
                logger.error(f"Failed to save settings to database: {e}")
                await session.rollback()
                raise

    async def get_setting(self, key: str, default=None) -> Any:
        """
        Получает значение настройки по ключу из БД.
        """
        try:
            settings = await self._get_latest_settings_from_db()
            return settings.get(key, default)
        except Exception as e:
            logger.error(f"Error getting setting '{key}': {e}")
            return default

    async def get_all_settings(self) -> Dict[str, Any]:
        """
        Получает все настройки из БД.
        """
        try:
            return await self._get_latest_settings_from_db()
        except Exception as e:
            logger.error(f"Error getting all settings: {e}")
            return {}

    async def set_setting(self, key: str, value: Any):
        """
        Устанавливает значение настройки в БД.
        """
        try:
            # Получаем текущие настройки
            current_settings = await self._get_latest_settings_from_db()
        except Exception:
            # Если нет настроек, создаём пустой словарь
            current_settings = {}

        # Обновляем значение
        current_settings[key] = value

        # Сохраняем в БД
        await self._save_settings_to_db(current_settings)

    async def update_settings(self, new_settings: Dict[str, Any]):
        """
        Обновляет все настройки в БД.
        """
        await self._save_settings_to_db(new_settings)

    @staticmethod
    def _format_env_value(value: Any) -> str:
        raw_value = "" if value is None else str(value)
        raw_value = raw_value.replace("\r", "\\r").replace("\n", "\\n")
        return json.dumps(raw_value, ensure_ascii=False)

    def _write_env_file(self, settings_data: Dict[str, Any], output_path: str) -> Dict[str, Any]:
        destination = Path(output_path).expanduser()
        destination.parent.mkdir(parents=True, exist_ok=True)

        valid_entries = []
        for key in sorted(settings_data.keys()):
            if not ENV_KEY_PATTERN.match(key):
                logger.warning(f"Skipping invalid env key: {key}")
                continue
            valid_entries.append((key, settings_data[key]))

        if not valid_entries:
            logger.warning("No valid settings keys for .env export")
            return {
                "status": "empty",
                "output_path": str(destination),
                "secrets_count": 0,
            }

        temp_basename = destination.name.lstrip(".") or "env"
        temp_path = destination.with_name(f".{temp_basename}.tmp")
        with temp_path.open("w", encoding="utf-8") as file:
            file.write(
                "# Generated by settings-bort at "
                f"{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}\n"
            )
            for key, value in valid_entries:
                file.write(f"{key}={self._format_env_value(value)}\n")

        temp_path.replace(destination)
        logger.info(f"Exported {len(valid_entries)} settings to {destination}")
        return {
            "status": "success",
            "output_path": str(destination),
            "secrets_count": len(valid_entries),
        }

    async def export_settings_to_env_file(self, output_path: str) -> Dict[str, Any]:
        if not output_path:
            return {"status": "error", "message": "BORT_ENV_OUTPUT_PATH is empty"}

        settings_data = await self.get_all_settings()
        if not settings_data:
            return {
                "status": "empty",
                "output_path": output_path,
                "secrets_count": 0,
            }
        return self._write_env_file(settings_data, output_path)

    @staticmethod
    def _load_settings_from_server(server_url: str, vehicle_id: str, timeout_sec: int = 30) -> Dict[str, Any]:
        response = requests.get(
            f"{server_url}/api/secrets/{vehicle_id}",
            timeout=timeout_sec,
        )
        response.raise_for_status()
        return response.json()

    @staticmethod
    def _calculate_checksum(settings_data: Dict[str, Any]) -> str:
        payload = json.dumps(
            settings_data or {},
            sort_keys=True,
            ensure_ascii=False,
            separators=(",", ":"),
        )
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()

    async def sync_with_vehicle_id(
        self,
        vehicle_id: str,
        settings_url: str = "",
        force: bool = False,
    ) -> Dict[str, Any]:
        if not vehicle_id:
            return {
                "status": "error",
                "message": "vehicle_id is required",
            }

        server_url = settings_url.strip() if settings_url else ""
        if not server_url:
            try:
                server_url = await RuntimeConfigManager().get_settings_url()
            except Exception:
                server_url = ""
        if not server_url:
            server_url = os.getenv('SETTINGS_URL', '')
        if not server_url:
            return {
                "status": "error",
                "message": "SETTINGS_URL is not set",
                "vehicle_id": vehicle_id,
            }

        try:
            remote_settings = await asyncio.to_thread(
                self._load_settings_from_server,
                server_url,
                vehicle_id,
            )
            remote_checksum = self._calculate_checksum(remote_settings)

            local_settings = await self.get_all_settings()
            local_checksum = self._calculate_checksum(local_settings) if local_settings else ""

            if not force and local_settings and local_checksum == remote_checksum:
                return {
                    "status": "no_change",
                    "vehicle_id": vehicle_id,
                    "checksum": remote_checksum,
                    "secrets_count": len(remote_settings),
                }

            await self._save_settings_to_db(remote_settings)

            export_result: Dict[str, Any] = {}
            output_path = os.getenv("BORT_ENV_OUTPUT_PATH", "").strip()
            if output_path:
                export_result = self._write_env_file(remote_settings, output_path)
                if export_result.get("status") != "success":
                    return {
                        "status": "error",
                        "message": "Failed to export env file",
                        "vehicle_id": vehicle_id,
                        "checksum": remote_checksum,
                        "secrets_count": len(remote_settings),
                        "export": export_result,
                    }

            return {
                "status": "updated",
                "vehicle_id": vehicle_id,
                "checksum": remote_checksum,
                "secrets_count": len(remote_settings),
                "export": export_result,
            }
        except requests.exceptions.RequestException as exc:
            return {
                "status": "error",
                "message": f"Error loading settings for vehicle_id={vehicle_id}: {exc}",
                "vehicle_id": vehicle_id,
            }
        except Exception as exc:
            return {
                "status": "error",
                "message": f"Unexpected error during sync_with_vehicle_id: {exc}",
                "vehicle_id": vehicle_id,
            }

    async def init_with_vehicle_id(self, vehicle_id: str, settings_url: str = "") -> bool:
        """
        Инициализирует настройки для конкретного vehicle_id.
        """
        result = await self.sync_with_vehicle_id(
            vehicle_id=vehicle_id,
            settings_url=settings_url,
            force=True,
        )
        if result.get("status") in {"updated", "no_change"}:
            logger.info(f"Successfully initialized settings for vehicle_id={vehicle_id}")
            return True
        logger.error(result.get("message", "init_with_vehicle_id failed"))
        return False
