---
- name: Install GitLab Runner
  ansible.builtin.import_tasks: install.yml

- name: Prepare GitLab Runner SSH files
  ansible.builtin.import_tasks: ssh.yml

- name: Register GitLab Runner
  ansible.builtin.import_tasks: register.yml

