---
deploy_lock_agent_enabled: false
deploy_lock_agent_dir: /srv/deploy-lock-agent
deploy_lock_agent_compose_filename: docker-compose.yaml
deploy_lock_agent_compose_path: "{{ deploy_lock_agent_dir }}/{{ deploy_lock_agent_compose_filename }}"
deploy_lock_agent_image: registry.dmi-msk.ru/base-images:deploy-lock-agent-4c75aeac
deploy_lock_agent_container_name: deploy-lock-agent
deploy_lock_agent_restart_policy: unless-stopped
deploy_lock_agent_user: root
deploy_lock_agent_network_name: docker-agent-network
deploy_lock_agent_docker_socket: /var/run/docker.sock
deploy_lock_agent_compose_up: false
deploy_lock_agent_defaults:
  deploy_lock_url: ""
  deploy_lock_token: ""
  deploy_lock_env_key: ""
  server_ip: null
deploy_lock_agent_hosts: {}

