mqtt {
  port = 1883
  max_connections = 1024000

  lmq_size = 10000
  aio_threads = 16
}

listeners {
  tcp {
    default {
      bind = "0.0.0.0:1883"
    }
  }
  ws {
    default {
      bind = "0.0.0.0:8083"
    }
  }
}

http_server {
  enable = true
  port = 8081
}