## NanoMQ Configuration File

mqtt {
  port = 1883
  max_connections = 1024000
  max_packet_size = 10485760
  keepalive_backoff = 1.25
  max_inflight_messages = 1000
  max_queued_messages = 5000
  retry_interval = 5
  
  lmq_size = 10000
  aio_threads = 16
}

websocket {
  enable = true
  port = 8083
  path = "/mqtt"
}

http_server {
  enable = true
  port = 8081
  username = "admin"
  password = "public"
}

log {
  to = [console]
  level = info
}

auth {
  allow_anonymous = true
  clean_start = false
}
