// Code generated by MockGen. DO NOT EDIT.
// Source: wifi-event-dispatcher/server/serverpb (interfaces: EventDispatchServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=bort/internal/grpc/mock_client_test.go -package=grpc wifi-event-dispatcher/server/serverpb EventDispatchServiceClient
//

// Package grpc is a generated GoMock package.
package grpc

import (
	context "context"
	reflect "reflect"
	serverpb "wifi-event-dispatcher/server/serverpb"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockEventDispatchServiceClient is a mock of EventDispatchServiceClient interface.
type MockEventDispatchServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockEventDispatchServiceClientMockRecorder
	isgomock struct{}
}

// MockEventDispatchServiceClientMockRecorder is the mock recorder for MockEventDispatchServiceClient.
type MockEventDispatchServiceClientMockRecorder struct {
	mock *MockEventDispatchServiceClient
}

// NewMockEventDispatchServiceClient creates a new mock instance.
func NewMockEventDispatchServiceClient(ctrl *gomock.Controller) *MockEventDispatchServiceClient {
	mock := &MockEventDispatchServiceClient{ctrl: ctrl}
	mock.recorder = &MockEventDispatchServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventDispatchServiceClient) EXPECT() *MockEventDispatchServiceClientMockRecorder {
	return m.recorder
}

// StreamBortGetEvents mocks base method.
func (m *MockEventDispatchServiceClient) StreamBortGetEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[serverpb.GetEventRequest, serverpb.GetEventResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamBortGetEvents", varargs...)
	ret0, _ := ret[0].(grpc.BidiStreamingClient[serverpb.GetEventRequest, serverpb.GetEventResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamBortGetEvents indicates an expected call of StreamBortGetEvents.
func (mr *MockEventDispatchServiceClientMockRecorder) StreamBortGetEvents(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamBortGetEvents", reflect.TypeOf((*MockEventDispatchServiceClient)(nil).StreamBortGetEvents), varargs...)
}

// StreamBortSendEvents mocks base method.
func (m *MockEventDispatchServiceClient) StreamBortSendEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[serverpb.SendEventRequest, serverpb.SendEventResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamBortSendEvents", varargs...)
	ret0, _ := ret[0].(grpc.BidiStreamingClient[serverpb.SendEventRequest, serverpb.SendEventResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamBortSendEvents indicates an expected call of StreamBortSendEvents.
func (mr *MockEventDispatchServiceClientMockRecorder) StreamBortSendEvents(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamBortSendEvents", reflect.TypeOf((*MockEventDispatchServiceClient)(nil).StreamBortSendEvents), varargs...)
}
